spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/exchange
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.dialect: com.odmytrenko.model.H2DialectCustom

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always

server:
  port: 8888

providers:
  finance:
    title: Finance.ua
    link: https://finance.ua/
    url: http://resources.finance.ua/ru/public/currency-cash.json
  kurs:
    title: Kurs.com.ua
    link: https://kurs.com.ua/
    url: https://kurs.com.ua/bank/