spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/exchange
    username: sa
    password:

server:
  port: 8888

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: com.odmytrenko.model.H2DialectCustom

providers:
  finance:
    name: Finance.ua
    link: https://finance.ua/
  kurs:
    name: Kurs.com.ua
    link: https://kurs.com.ua/